---
title: 'Modelling'
output:
    html_document:
        toc: TRUE
        toc_float: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

```{r, message=FALSE, echo=FALSE, warning=FALSE}
library(data.table)
library(tidyverse)
library(knitr)
library(ggplot2)
library(caret)
library(mgcv)
library(car)
library(leaps)
library(MASS)
library(rpart)
library(rpart.plot)
library(randomForest)
library(gbm)
library(xgboost)
library(doParallel)
library(plotly)
```

```{css, echo = FALSE}
caption {
      color: black;
    }
```

```{r}
restaurants <- read.csv("data/cleaned_restaurants.csv") # from `data-wrangling.Rmd`
```

```{r}
restaurants <- restaurants %>% 
  mutate(
    price_level = if_else(is.na(price_level), "Unknown", price_level)) %>% 
  mutate (
    price_level = factor(price_level, 
                         levels = c("Low", "Medium", "High", "Very High", "Unknown")),
    size_level = factor(size_level, 
                         levels = c("Single Location", "Small Chain", 
                                    "Medium Chain", "Large Chain")),
    type = factor(type),
    cuisine = factor(cuisine)
  )
```

```{r}
set.seed(9900)
train <- sample(1:nrow(restaurants), round(0.7 * nrow(restaurants)))

rest_train <- restaurants[train, ]
rest_test <- restaurants[-train, ]
```


# Linear Models
## Baseline
```{r}
base_lm <- lm(rating ~ distance + longitude + latitude + price_level + 
                review_count + type + cuisine + size_level, data = rest_train)

kable(coef(base_lm))
```

```{r}
# RMSE
predictions <- predict(base_lm, newdata = rest_train)
sqrt(mean((rest_train$rating - predictions)^2))
```

```{r}
vif(base_lm)
```


## Automated Selection
```{r}
stepAIC(base_lm, direction = "both", k = 2)
```

```{r}
auto_lm <- lm(formula = rating ~ price_level + review_count + type + cuisine + 
    size_level, data = rest_train)
summary(auto_lm)
```

```{r}
# RMSE
predictions <- predict(auto_lm, newdata = rest_train)
sqrt(mean((rest_train$rating - predictions)^2))
```

## GLMM with neighbourhood random effect
```{r}
rest_train$neighbourhood <- as.factor(rest_train$neighbourhood)
rand_gam <- gam(rating ~ distance + longitude + latitude + price_level + 
                review_count + type + cuisine + size_level 
                + s(neighbourhood, bs = "re"), 
                data = rest_train)

summary(rand_gam)
```

```{r}
# RMSE
predictions <- predict(rand_gam, newdata = rest_train)
sqrt(mean((rest_train$rating - predictions)^2))
```

# Tree Models
## Regression Tree
```{r}
rest_tree <- rpart(
  rating ~ distance + longitude + latitude + price_level + 
                review_count + type + cuisine + size_level, 
  data = rest_train, 
  method = "anova", 
  control = list(
    minsplit = 10, 
    minbucket = 3,
    cp = 0,
    xval = 10
  )
)

rpart.plot(rest_tree)
```

```{r}
optimalcp = rest_tree$cptable[which.min(rest_tree$cptable[,"xerror"]), "CP"]
rest_tree_prune <- prune(rest_tree, cp = optimalcp)
rpart.plot(rest_tree_prune)
```

## Random Forest
```{r}
set.seed(999)
rest_rf <- randomForest(
  rating ~ distance + longitude + latitude + price_level + 
                review_count + type + cuisine + size_level,
  data = rest_train,
  na.action = na.omit,
  ntree = 1000
)
```

```{r}
varImpPlot(rest_rf)
```

## XGBoost
```{r}
set.seed(999)
rest_boost0.001 = gbm(
  rating ~ distance + longitude + latitude + price_level + 
                review_count + type + cuisine + size_level,
  data = rest_train,
  distribution = "gaussian", 
  n.trees = 1000,
  interaction.depth = 1,
  shrinkage = 0.001,
  cv.folds = 5)
```

```{r}
plot(rest_boost0.001$train.error, col = "red4",
     type = "l", lwd = 3, ylab = "Error", 
     main = "Training Error vs. Cross-Validation Error Across Boosting Iterations")
lines(rest_boost0.001$cv.error, col = "steelblue", lwd = 3)
legend("topright", legend = c("Training Error", "CV Error"), 
       col = c("red4", "steelblue"), lwd = 3, bty = "n")
```

```{r}
set.seed(999)
rest_boost0.01 = gbm(
  rating ~ distance + longitude + latitude + price_level + 
                review_count + type + cuisine + size_level,
  data = rest_train,
  distribution = "gaussian", 
  n.trees = 1000,
  interaction.depth = 1,
  shrinkage = 0.01,
  cv.folds = 5)
```

```{r}
plot(rest_boost0.01$train.error, col = "red4",
     type = "l", lwd = 3, ylab = "Error", 
     main = "Training Error vs. Cross-Validation Error Across Boosting Iterations")
lines(rest_boost0.01$cv.error, col = "steelblue", lwd = 3)
legend("topright", legend = c("Training Error", "CV Error"), 
       col = c("red4", "steelblue"), lwd = 3, bty = "n")
```

```{r}
set.seed(999)
rest_boost0.1 = gbm(
  rating ~ distance + longitude + latitude + price_level + 
                review_count + type + cuisine + size_level,
  data = rest_train,
  distribution = "gaussian", 
  n.trees = 1000,
  interaction.depth = 1,
  shrinkage = 0.1,
  cv.folds = 5)
```

```{r}
plot(rest_boost0.1$train.error, col = "red4",
     type = "l", lwd = 3, ylab = "Error", 
     main = "Training Error vs. Cross-Validation Error Across Boosting Iterations")
lines(rest_boost0.1$cv.error, col = "steelblue", lwd = 3)
legend("topright", legend = c("Training Error", "CV Error"), 
       col = c("red4", "steelblue"), lwd = 3, bty = "n")
```

```{r}
plot_data <- data.frame(
  shrinkage = c(0.001, 0.01, 0.1), 
  trainingMSE = c(
    rest_boost0.001$train.error[1000],
    rest_boost0.01$train.error[1000],
    rest_boost0.1$train.error[1000]
  )
)

plot_data %>% 
  ggplot(aes(x = shrinkage, y = trainingMSE)) +
  geom_line(color = "salmon", linewidth = 1) +         
  geom_point(size = 3, color = "salmon") +            
  labs(
    title = "Training MSE vs. Shrinkage Parameter",
    x = "Shrinkage Parameter",
    y = "Training MSE"
  ) +
  theme_light()
```

```{r}
par(cex.axis=0.6)
summary(rest_boost0.01, las = 1)
```

```{r}
cl <- makePSOCKcluster(8) 
registerDoParallel(cl)

train_control <- trainControl(method = "cv", number = 10, search ="grid",
                              allowParallel = TRUE)

tune_grid <-  expand.grid(max_depth = c(1, 3, 5, 7), 
                        nrounds = (1:10)*50, 
                        eta = c(0.01,0.1,0.3), 
                        gamma = 0, 
                        subsample = 1,
                        min_child_weight = 1,
                        colsample_bytree = 0.6 
                        )

rest_xgb <- caret::train(
  rating ~ distance + longitude + latitude + price_level + 
                review_count + type + cuisine + size_level,
  data = rest_train,
  method="xgbTree",
  trControl = train_control,
  tuneGrid = tune_grid,
  na.action = na.exclude,
  verbosity = 0)

stopCluster(cl)
```


```{r}
# overall RMSE plot
RMSEplot <- rest_xgb$results %>% 
  mutate(param_combo = paste0("eta:", eta, ", max_depth:", max_depth)) %>%
  ggplot(aes(x = nrounds, y = RMSE, 
             color = factor(param_combo))) +
  geom_line(linewidth = 1) +
  geom_point() +
  labs(title = "RMSE vs. Number of Boosting Rounds",
       subtitle = "by Learning Rate (eta) and Max Tree Depth for XGBoost",
       x = "Number of Rounds (nrounds)",
       y = "RMSE",
       color = "Hyperparameter Combination") +
  theme_light() +
  theme(plot.title = element_text(face = "bold"))

ggplotly(RMSEplot) # make interactive to toggle different views on the same plot
```


```{r}
# best hyperparameters
rest_xgb$bestTune
```

```{r}
varimp <- varImp(rest_xgb, scale = FALSE)
plot(varimp)
```

```{r}
# make predictions from each model
yhat_lmbase <- predict(base_lm, newdata = rest_test)
yhat_autolm <- predict(auto_lm, newdata = rest_test)
yhat_glmm <- predict(rand_gam, newdata = rest_test)
yhat_regtree <- predict(rest_tree_prune, newdata = rest_test)
yhat_rf <- predict(rest_rf, newdata = rest_test)
yhat_boost <- predict(rest_boost0.01, newdata = rest_test)
yhat_xgb <- predict(rest_xgb, newdata = rest_test)
```
```{r}
# make predictions from each model
yhat_lmbase_tr <- predict(base_lm, newdata = rest_train)
yhat_autolm_tr <- predict(auto_lm, newdata = rest_train)
yhat_glmm_tr <- predict(rand_gam, newdata = rest_train)
yhat_regtree_tr <- predict(rest_tree_prune, newdata = rest_train)
yhat_rf_tr <- predict(rest_rf, newdata = rest_train)
yhat_boost_tr <- predict(rest_boost0.01, newdata = rest_train)
yhat_xgb_tr <- predict(rest_xgb, newdata = rest_train)
```

```{r}
test_MSE_table <- data.frame(
  Method = c(
    "Linear Regression",
    "Auto Lin Reg",
    "GLMM",
    "Regression Tree",
    "Random Forest",
    "Boosting",
    "XGBoost"
  ),
  `Train RMSE` = c(
    sqrt(mean((yhat_lmbase_tr - rest_train$rating)^2)),
    sqrt(mean((yhat_autolm_tr - rest_train$rating)^2)),
    sqrt(mean((yhat_glmm_tr - rest_train$rating)^2)),
    sqrt(mean((yhat_regtree_tr - rest_train$rating)^2)),
    sqrt(mean((yhat_rf_tr - rest_train$rating)^2)),
    sqrt(mean((yhat_boost_tr - rest_train$rating)^2)),
    sqrt(mean((yhat_xgb_tr - rest_train$rating)^2))
  ),
  `Test RMSE` = c(
    sqrt(mean((yhat_lmbase - rest_test$rating)^2)),
    sqrt(mean((yhat_autolm - rest_test$rating)^2)),
    sqrt(mean((yhat_glmm - rest_test$rating)^2)),
    sqrt(mean((yhat_regtree - rest_test$rating)^2)),
    sqrt(mean((yhat_rf - rest_test$rating)^2)),
    sqrt(mean((yhat_boost - rest_test$rating)^2)),
    sqrt(mean((yhat_xgb - rest_test$rating)^2))
  ),
  check.names = FALSE
)

kable(test_MSE_table, digits = 3, caption = "RMSE Comparison Across Methods")
```